### ISSUE TITLE
question about long-term tasks management

### ISSUE THREAD

**Issue by tshu-w** [rougier/emacs-gtd#18]
Thx you for sharing you GTD setup with Org mode. It's really useful.

I have long struggled with maintaining long-term tasks (reading a book or taking a course). If I put it in Agenda, it's too serious and takes attention away from the important things of the day. I can't really estimate the time spent if I put it in Next Actions, and the task of reading a book seems to go against the [SMART criteria](https://en.wikipedia.org/wiki/SMART_criteria).

For these tasks (and there are many) I wish I could just pick one and do it when I have time. I would like to hear from you about your strategy for handling these long-term tasks and how to choose one to do.

**Comment by rougier** [comment]
Well, I've the same problem actually and I tend to have a separate long-term file where I record such tasks. My problem is to display them properly and to have the motivation to look at them. If they're always present, you tend to not notice them anymore.

**Comment by tshu-w** [comment]
Hi, thank you for you reply. Currently I limit the project I work on and the next actions for each project. I look forward to seeing your late practice updates.
