### ISSUE TITLE
Invalid capture template.

### ISSUE THREAD

**Issue by believerd** [rougier/emacs-gtd#2]
`
(setq org-capture-templates
      '(("i" "Inbox" entry  (file "inbox.org")
         (concat "* TODO %?\n"
                 "/Entered on/ %U"))))
`
It seems like a "concat" problem, I removed it and it works fine now.

**Comment by believerd** [comment]
I'm running Emacs 27.1 with Org-mode version 9.3.7.

**Comment by rougier** [comment]
Oh thank for the report. Can you make a PR ?
