### ISSUE TITLE
What is the meaning of '+' and quotation marks in C-c C-w + "J.Doe" + tab + "T" + tab

### ISSUE THREAD

**Issue by yubrshen** [rougier/emacs-gtd#24]
In the section on moving tasks, please explain the meaning of C-c C-w + "J.Doe" + tab + "T" + tab
I assume that the space in the above is not literate (no needed to type).
How about the quotation marks and plus sign? I tried to type them, it causes no completion at all.

**Comment by yubrshen** [comment]
With my emacs/doom setup, probably a modern auto completion (verticle?), the following literate keys works for me:
C-cC-w projects.org tasks doe
(then Enter)

**Comment by whatacold** [comment]
> C-c C-w + "J.Doe" + tab + "T" + tab

It just means "and then type ..." for + signs, and you can just ignore the double quote marks while you're typing, I believe.

What the whole string means is to type `C-c C-w` (the `org-refile` command) and then select your target parent node, a Tasks if you follow the setup.
